language: c
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - autoconf
          - automake
          - libtool
          - guile-2.0-dev
      script:
        - sh autogen.sh --prefix=`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local
    - os: osx
      install:
        - brew update
        - brew install guile
      script:
        - sh autogen.sh --prefix=`pwd`/.local
        - make && make check && make install
        - rm -rf * ~/.local

after_script:
  - PRISM_LOG=${TRAVIS_BUILD_DIR}/utils/test-prism.log
  - if [[ -e ${PRISM_LOG} ]]; then cat ${PRISM_LOG}; fi
