site_name: libctl Documentation
site_author: libctl Developers
repo_url: https://github.com/NanoComp/libctl/

docs_dir: 'doc/docs'
site_dir: 'doc/site'

theme:
  name: readthedocs

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript:
 - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'

pages:
- Overview: index.md
- Introduction: Introduction.md
- Installation: Installation.md
- Basic User Experience: Basic_User_Experience.md
- Advanced User Experience: Advanced_User_Experience.md
- User Reference: User_Reference.md
- Developer Experience: Developer_Experience.md
- Guile and Scheme Information: Guile_and_Scheme_Information.md
- License and Copyright: License_and_Copyright.md
