site_name: libctl Documentation
site_author: S. G. Johnson et al.
repo_url: https://github.com/stevengj/libctl/

docs_dir: 'doc/docs'
site_dir: 'doc/site'

theme_dir: 'doc/libctl-mkdocs-theme'
theme: readthedocs

python:
   version: 2 # for unicode
   setup_py_install: True

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript:
 - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'
 - 'js/mathjaxhelper.js'
 - 'js/extra.js'

pages:
- Overview: index.md
- Introduction: Introduction.md
- Installation: Installation.md
- Basic User Experience: Basic_User_Experience.md
- Advanced User Experience: Advanced_User_Experience.md
- Developer Experience: Developer_Experience.md
- User Reference: User_Reference.md
- Guile and Scheme Information: Guile_and_Scheme_Information.md
- License and Copyright: License_and_Copyright.md
- Release Notes: Release_Notes.md
